FROM python:3.8

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8888

CMD ["jupyter", "notebook", "dok", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

