# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port for Jupyter Notebook (default is 8888)
EXPOSE 8888

# Run Jupyter Notebook with a specific notebook file when the container launches
CMD ["jupyter", "notebook", "dok", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

